# Sample workflow for building and deploying a Next.js site to GitHub Pages
#
# To get started with Next.js see: https://nextjs.org/docs/getting-started
#
name: Deploy Frontend to Vercel and Backend to Heroku

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Deploy Frontend to Vercel
  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: Frontend/package-lock.json
      - name: Install dependencies
        run: cd Frontend && npm ci
      - name: Lint
        run: cd Frontend && npx eslint . --ext .ts,.tsx,.js,.jsx
      - name: Test
        run: cd Frontend && npm run test
      - name: Build
        run: cd Frontend && npm run build
      - name: Deploy to Vercel (Frontend)
        uses: amondnet/vercel-action@v25.1.1
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: --prod --yes
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_FRONTEND }}
          working-directory: Frontend

  # Build and Deploy Backend
  build_backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: npm
          cache-dependency-path: Backend/package-lock.json
      - name: Install dependencies
        run: cd Backend && npm ci
      - name: Test Backend
        run: cd Backend && npm test
      - name: Build Backend
        run: cd Backend && npm run build
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.15
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: sih-ps25092-ruhv1-backend  # Replace with your actual Heroku app name
          heroku_email: madhavk005@gmail.com  # Replace with your email for notifications
